### ISSUE TITLE
Autonomous Tagging of StackOverflow Questions project

### ISSUE THREAD

**Issue by harssh1029** [NirantK/awesome-project-ideas#15]
Hey, How to start this project , please tell some article , videos , topic to study before starting and if you can provide code that would be helpful.

**Comment by ankitsharma07** [comment]
@harssh1029 you can refer to [this](https://www.kaggle.com/stackoverflow/stacksample) dataset available on kaggle. [Relevant](https://www.kaggle.com/anil777/stackoverflow-tagging-questions/notebook) notebook to look for.

**Comment by NirantK** [comment]
Thanks for replying @ankitsharma07
