### ISSUE TITLE
sorted list?

### ISSUE THREAD

**Issue by mlkorra** [NirantK/awesome-project-ideas#2]
Is the list sorted from beginner to expert? If not,it would be helpful if you could do that.

**Comment by NirantK** [comment]
Thanks for the suggestion @mlkorra. I considered doing that in the beginning but realised that would brings in my own bias of what is beginner and what is not. I'd rather have people do the work and form their opinions while I give them the information to do so. 

For instance, I might consider most image classification tasks which can finetuned from ImageNet to be beginner stuff. It can probably be done in a weekend with pre-trained weights and decent GPU RAM. 
A lot of people consider that to be worthy of Master's Thesis. 

If you have a better way out of this dilemma please do share the same :)
