### ISSUE TITLE
De-anonymization

### ISSUE THREAD

**Issue by hmntstr** [NirantK/awesome-project-ideas#3]
Hi,

I'm interested in implementing this project. So, can you please share me this project for de-anonymization of emails with proper readme file for guidance?

**Comment by NirantK** [comment]
Hey @hmntstr you can find the dataset here: https://www.cs.cmu.edu/%7E./enron/

Download the emails and split into train, valid and test. Train a model which predicts the sender email id. This is your main modeling task. Hope this helps! 

Closing this unless you have more questions.
